site_name: Documentação Softdes-Desafios
nav:
    - Home: docs/user.md
    - Usuário-Professor: docs/user_teacher.md
    - Usuário-Aluno: docs/user_student.md
    - Desenvolvedor: docs/dev.md
theme: readthedocs